import sys

from PySide6.QtWidgets import QApplication, QMainWindow

from ui_counter import Ui_MainWindow  # generated by pyside6-uic


class CounterApp(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)  # sets up all widgets

        # Connect buttons to methods
        self.ui.btn_increase.clicked.connect(self.increase_counter)
        self.ui.btn_reset.clicked.connect(self.reset_counter)

        # Counter variable
        self.counter = 0
        self.ui.lbl_counter.setText(str(self.counter))

    def increase_counter(self):
        self.counter += 1
        self.ui.lbl_counter.setText(str(self.counter))

    def reset_counter(self):
        self.counter = 0
        self.ui.lbl_counter.setText(str(self.counter))


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = CounterApp()
    window.show()
    sys.exit(app.exec())
